import { intro, outro, text } from '@clack/prompts';
import ora from 'ora';
import fs from 'fs';
import path from 'path';
import chalk from 'chalk';
import { logger } from '../utils/logger';
import { detectProjects } from '../utils/monorepo';
import { generateMarkdown } from '../generators/markdown';
import { groupDependencies } from '../utils/dependencies';
import { generateNextJsMarkdown } from '../generators/nextjs-markdown';
import { scanProject, getEnvKeysForMarkdown } from '../scan-project';

export async function initCommand() {
  let spinner: any = null;

  try {
    intro(chalk.cyan('📝  Lorex - Your Project Memory\n'));

    const oneliner = (await text({
      message: 'Describe your project in one line',
    })) as string;

    if (!oneliner || oneliner.length === 0) {
      outro(chalk.red('❌ No description provided'));
      process.exit(1);
    }

    console.log('');

    const projectTargets = detectProjects(process.cwd());

    spinner = ora(
      chalk.cyan(
        `Scanning ${projectTargets.length} project${projectTargets.length > 1 ? 's' : ''}...`
      )
    ).start();
    const scanStart = Date.now();

    const results: Array<{ outputFile: string; result: Awaited<ReturnType<typeof scanProject>> }> =
      [];
    for (const target of projectTargets) {
      spinner.text = `Scanning ${path.basename(target.root)}...`;
      const result = await scanProject(target.root);
      results.push({ outputFile: target.outputFile, result });
    }

    spinner.succeed(chalk.green('Projects scanned successfully'));

    for (const { outputFile, result } of results) {
      const outputPath = path.join(process.cwd(), outputFile);
      let markdown: string;

      try {
        if (result.isNextJsProject && result.nextJsRoutes) {
          const grouped = groupDependencies(
            result.packageInfo.dependencies,
            result.packageInfo.devDependencies
          );

          markdown = generateNextJsMarkdown({
            projectName: result.packageInfo.name || 'Project',
            projectDescription: oneliner,
            nextJsRoutes: result.nextJsRoutes,
            structureTree: result.nextJsStructure || '',
            groupedPackages: grouped,
            authConfig: result.auth || { authType: 'None', providers: [], configFiles: [] },
            commits: result.commits || [],
            components: result.components || [],
            schema: result.schema,
            envKeys: getEnvKeysForMarkdown(result.envKeys),
          });
        } else {
          markdown = generateMarkdown({
            oneliner,
            packageInfo: result.packageInfo,
            structure: result.structure,
            schema: result.schema,
            envKeys: result.envKeys,
            routes: result.routes,
            gitLog: result.gitLog,
            scripts: result.scripts,
            deployment: result.deployment,
          });
        }
      } catch (error) {
        markdown = `# ${result.packageInfo.name || 'Project'}

${oneliner}

## Error
Failed to generate documentation: ${(error as Error).message}

---
*Generated by [lorex-cli](https://github.com/justpriyanshu/lorex-cli)*`;
      }

      fs.writeFileSync(outputPath, markdown);
    }

    const duration = (Date.now() - scanStart) / 1000;

    let totalRoutes = 0;
    for (const { result } of results) {
      if (result.isNextJsProject && result.nextJsRoutes) {
        totalRoutes +=
          (result.nextJsRoutes.pageRoutes?.length || 0) +
          (result.nextJsRoutes.apiRoutes?.length || 0);
      } else {
        totalRoutes += result.routes.length;
      }
    }

    const totalModels = results.reduce(
      (sum, entry) => sum + (entry.result.schema?.models.length ?? 0),
      0
    );
    const totalComponents = results.reduce(
      (sum, entry) => sum + (entry.result.components?.length ?? 0),
      0
    );

    console.log('');
    if (results.length === 1) {
      logger.success(
        `Documentation created at ${chalk.bold(path.join(process.cwd(), results[0].outputFile))}`
      );
    } else {
      logger.success(`Documentation created for ${results.length} projects:`);
      for (const { outputFile } of results) {
        console.log(`  → ${outputFile}`);
      }
    }
    console.log('');
    console.log(
      `✓ Generated in ${duration.toFixed(1)}s (${totalRoutes} routes · ${totalModels} models · ${totalComponents} components)`
    );
    console.log('');
    outro(chalk.cyan('Run lorex copy to paste into any AI chat.'));
  } catch (error) {
    if (spinner) {
      spinner.fail(chalk.red('Error scanning project'));
    }
    logger.error(String(error));
    process.exit(1);
  }

  process.exit(0);
}
